# Generated by Django 4.0.1 on 2022-01-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svceClubMgmtApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('yos', models.IntegerField()),
                ('sec', models.CharField(max_length=2)),
                ('regno', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=11)),
                ('clgmailid', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='president_username',
            field=models.CharField(default='shri', max_length=30),
        ),
        migrations.AddField(
            model_name='club',
            name='recruiting',
            field=models.IntegerField(default=0),
        ),
    ]
