# Generated by Django 4.0.1 on 2022-01-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svceClubMgmtApp', '0002_volunteers_club_president_username_club_recruiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteers',
            name='clubname',
            field=models.CharField(default='no club', max_length=20),
        ),
    ]
